### ISSUE TITLE
How frequent does it update its data?

### ISSUE THREAD

**Issue by arash-mehrabi-z** [aashari/mq-covid-19#1]
First of all thanks for this very good api.  
I have 2 questions:  
1. I want to ask how frequent does it updates its data? Every day?  
2. Exactly when does it updates its data?  
By updating I mean adding new data, today's data.

**Comment by aashari** [comment]
It will collect the data each minute from these sources:
- github.com/CSSEGISandData/COVID-19
- worldometers.info/coronavirus

Sometimes the github.com/CSSEGISandData/COVID-19, doesn't really realtime, then I added new support worldometers.info/coronavirus to make it nearly realtime

**Comment by arash-mehrabi-z** [comment]
You done well, thank you.
