### ISSUE TITLE
Statistics about countries are true but are wrong about provinces

### ISSUE THREAD

**Issue by arash-mehrabi-z** [aashari/mq-covid-19#2]
Canada's data is correct about the whole country but it is incorrect about provinces. It seems your code always sums all provinces of each countries statistics and stores them in provinces too.  
I mean Canada's confirmed cases is 341 right now and it is true but the Ontario's cases (one of the provinces of Canada) is 104 according to JHU CSSE but your code shows 341 too. In fact it shows 341 for all provinces of Canada.

**Comment by aashari** [comment]
Will fix the issue, thanks for reporting

**Comment by aashari** [comment]
I fixed your issue in this commit: https://github.com/aashari/mq-covid-19/commit/f760558486a8b267f259892072158546355163fe
